#!/bin/sh
rails generate scaffold users username password_digest first_name last_name email course role:integer github

rails generate scaffold projects title body:text user:references image github

rails generate scaffold news title body:text user:references

rails d scaffold users username password_digest first_name last_name email course role:integer github

rails d scaffold projects title body:text user:references image github

rails d scaffold news title body:text user:references

# Table name: users
#
#  id              :integer          not null, primary key
#  username        :string
#  password_digest :string
#  first_name      :string
#  last_name       :string
#  email           :string
#  course          :string
#  role            :integer
#  github          :string
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
